### ISSUE TITLE
Endogenous editing or in-vitro constructs

### ISSUE THREAD

**Issue by ahwagner** [ave-dcd/mave_vocabulary#2]
This section of the README describes the use of controlled vocabulary terms for endogenous edit or in-vitro construct methods for library generation:
https://github.com/ave-dcd/mave_vocabulary/blob/96d3dcc0f59330ddd1d2ddcbf0b5ef9ff54a5cc4/README.md?plain=1#L137-L139

My understanding is that an experiment may generate a library via one of these mechanisms, not both. This has implications in schema, as the fields and valuesets required for endogenous editing experiments are distinct from in-vitro construct experiments. Examples of experiments where both types of library generation methods are used together would be very informative.

In addition, these types refer to discrete subschemas for the `VariantLibrary.generationMethod`:
https://github.com/ave-dcd/mave_vocabulary/blob/96d3dcc0f59330ddd1d2ddcbf0b5ef9ff54a5cc4/schema/experiment.yml#L197-L201

We should revise the README or schema to match, I suggest changing the README as the subschema approach allows for differences in required fields for _in-vitro_ vs endogenous edit library methods.

**Comment by afrubin** [comment]
Agreed. Closed by https://github.com/ave-dcd/mave_vocabulary/pull/6
