### ISSUE TITLE
Delivery method - one or many

### ISSUE THREAD

**Issue by ahwagner** [ave-dcd/mave_vocabulary#4]
The README indicates that an experiment may have multiple mechanisms of delivering the variant induction machinery or construct into the cell/organism:

https://github.com/ave-dcd/mave_vocabulary/blob/96d3dcc0f59330ddd1d2ddcbf0b5ef9ff54a5cc4/README.md?plain=1#L174-L183

This is currently not supported by the schema and I am not aware of any examples that support this case. Lacking this, I think the README should be updated to reflect the schema.

**Comment by afrubin** [comment]
Closed by https://github.com/ave-dcd/mave_vocabulary/pull/6
